FROM nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04

RUN apt update \
    && apt install python3 -y \
    && apt install python3-pip -y \
    && apt install libpq-dev -y

ENV PATH=/root/.local/bin:${PATH}

RUN pip install poetry \
    && poetry install

WORKDIR /home/python/TFG

VOLUME [ "/home/python/TFG" ]

ENTRYPOINT poetry run invoke train
