FROM nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu20.04

RUN apt update && apt install -y \
    git \
    python3 \
    python3-pip \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install poetry

ENV PATH=/root/.local/bin:${PATH}

WORKDIR /home/python/TFG

COPY pyproject.toml poetry.lock ./

RUN poetry export -f requirements.txt --without-hashes | pip install -r /dev/stdin

ENTRYPOINT invoke train
