version:

services:
    optuna-db:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: optuna
        POSTGRES_USER: optuna
        POSTGRES_DB: optuna

    train-container:
        build:
          context: .
          dockerfile: Dockerfile.train
        shm_size: 10.11gb
        env_file: .env
        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
