FROM nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04

RUN apt update \
    && apt install python3 -y \
    && apt install python3-pip -y \
    && apt install libpq-dev -y

ENV PATH=/root/.local/bin:${PATH}

WORKDIR /home/python

COPY pyproject.toml poetry.lock ./

RUN pip install poetry \
    && poetry install --no-dev

VOLUME [ "/home/python/TFG" ]
