version: '3.9'

services:
    mlflow-db:
        image: mysql
        restart: always
        ports: 
            - 3306:3306
        volumes:
            - mysql_vol:/var/lib/postgresql/data
        env_file: .env

    mlflow:
        build: .
        depends_on:
            - mlflow-db
        restart: always
        ports:
            - 80:5000
        env_file: .env

volumes:
    mysql_vol: {}
